"""Offline licence verification for the paid Service Mate add-on.

Runsheet Pilot's core flow (upload → parse → create playlist) is free.
Service Mate (pushing cues to GeekMagic LAN clocks) is a paid add-on with
a 14-day free trial.

How it works — entirely offline, no server:
  - A single Ed25519 keypair exists. The PRIVATE key lives only on the
    owner's machine (tools/secrets/, gitignored) and signs licence keys.
    The PUBLIC key is embedded below and can only *verify* — safe to ship.
  - A licence key is `RP1.<base64url(payload)>.<base64url(signature)>`
    where payload is compact JSON like
    {"n":"Hillsong Brisbane","p":"service_mate","iat":"2026-06-01"}.
    The buyer's name is signed in, so tampering with it breaks the key —
    and the app can show "Licensed to <name>".
  - The app verifies the signature against the embedded public key. Valid
    + product == "service_mate" → unlocked, forever, offline.

Why offline: church AV booths are often offline during a service, and the
feature only talks to LAN clocks. Requiring internet to validate would be
self-defeating, and there's no server to run or pay for.

The trial: 14 days from first active use (first time the master switch is
turned on / the daemon first runs). The start date lives in settings.json
(`sm_trial_start`). A determined user could reset it by editing that file;
that's an accepted trade-off for a beta paywall — this is a fair gate, not
hard DRM.

`cryptography` (which provides Ed25519) already ships in the bundle as a
transitive dependency of pdfplumber, so this module adds no new runtime
dependency and needs no PyInstaller flag changes.
"""

import base64
import datetime as _dt
import json
import logging

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from .settings import load_settings, save_settings


log = logging.getLogger("pp_runsheet")

# ── Constants ───────────────────────────────────────────────────────────────
# Embedded Ed25519 public key (base64 of the 32 raw bytes). Verify-only —
# safe to commit. Generated by tools/generate_keypair.py; the matching
# private key is gitignored under tools/secrets/. Tests monkeypatch this.
_PUBLIC_KEY_B64 = "cNXaOyL4Xk7sCbEUiwb7pK/UqbNnsyu5Iawpk7ulizo="

_PREFIX = "RP1"            # licence-key format version tag
_PRODUCT = "service_mate"  # the feature this licence unlocks
TRIAL_DAYS = 14


# ── Encoding helpers (shared with tools/issue_license.py) ───────────────────
def _b64url_encode(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode("ascii")


def _b64url_decode(s: str) -> bytes:
    pad = "=" * (-len(s) % 4)
    return base64.urlsafe_b64decode(s + pad)


def _payload_bytes(payload: dict) -> bytes:
    """Canonical bytes for a payload — sorted keys, no whitespace — so the
    signer and verifier always hash the exact same bytes."""
    return json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")


def make_license(payload: dict, private_key) -> str:
    """Sign `payload` and return a pasteable RP1 licence key. Used only by
    the seller-side CLI (tools/issue_license.py) — the app never signs."""
    pb = _payload_bytes(payload)
    sig = private_key.sign(pb)
    return f"{_PREFIX}.{_b64url_encode(pb)}.{_b64url_encode(sig)}"


# ── Verification ────────────────────────────────────────────────────────────
def verify_license(key: str):
    """Return the decoded payload dict if `key` is a valid, correctly-signed
    licence; otherwise None. Never raises."""
    if not key or not isinstance(key, str):
        return None
    parts = key.strip().split(".")
    if len(parts) != 3 or parts[0] != _PREFIX:
        return None
    try:
        payload_bytes = _b64url_decode(parts[1])
        signature = _b64url_decode(parts[2])
    except Exception:
        log.info("Licence rejected: malformed base64")
        return None
    try:
        pub = Ed25519PublicKey.from_public_bytes(base64.b64decode(_PUBLIC_KEY_B64))
        pub.verify(signature, payload_bytes)  # raises on mismatch
    except Exception:
        log.info("Licence rejected: signature does not verify")
        return None
    try:
        return json.loads(payload_bytes.decode("utf-8"))
    except Exception:
        log.info("Licence rejected: payload is not valid JSON")
        return None


# ── Service Mate gate ───────────────────────────────────────────────────────
def service_mate_status() -> dict:
    """Pure read (no writes). Return a dict describing the Service Mate
    entitlement:
        {"state": "licensed"|"trial"|"trial_unstarted"|"expired",
         "licensed_to": str | None,
         "days_left": int | None,
         "key_invalid": bool}
    """
    s = load_settings()
    key = (s.get("license_key") or "").strip()
    key_invalid = False
    if key:
        payload = verify_license(key)
        if payload and payload.get("p") == _PRODUCT:
            return {"state": "licensed",
                    "licensed_to": payload.get("n") or "Licensed",
                    "days_left": None,
                    "key_invalid": False}
        # A key is present but doesn't verify (typo, wrong product, tampered).
        # Fall through to trial logic but flag it so the UI can warn.
        key_invalid = True

    start = (s.get("sm_trial_start") or "").strip()
    if not start:
        return {"state": "trial_unstarted", "licensed_to": None,
                "days_left": TRIAL_DAYS, "key_invalid": key_invalid}
    try:
        start_date = _dt.date.fromisoformat(start)
    except ValueError:
        # Corrupt date — be lenient and treat as not-yet-started.
        return {"state": "trial_unstarted", "licensed_to": None,
                "days_left": TRIAL_DAYS, "key_invalid": key_invalid}

    days_left = TRIAL_DAYS - (_dt.date.today() - start_date).days
    if days_left > 0:
        return {"state": "trial", "licensed_to": None,
                "days_left": days_left, "key_invalid": key_invalid}
    return {"state": "expired", "licensed_to": None,
            "days_left": 0, "key_invalid": key_invalid}


def service_mate_allowed() -> bool:
    """True when Service Mate may run (licensed or within trial)."""
    return service_mate_status()["state"] in (
        "licensed", "trial", "trial_unstarted")


def start_trial_if_needed() -> None:
    """Stamp `sm_trial_start = today` the first time the feature is actively
    used, unless the user is already licensed or the trial already started.
    Idempotent. Safe to call from the daemon tick + the enable route."""
    s = load_settings()
    if (s.get("license_key") or "").strip():
        return  # licensed — no trial needed
    if (s.get("sm_trial_start") or "").strip():
        return  # already counting
    today = _dt.date.today().isoformat()
    save_settings({"sm_trial_start": today})
    log.info("Service Mate %d-day trial started (%s)", TRIAL_DAYS, today)
